//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPD_Section
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int ITEM_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public int ITEM_TYPE_ID { get; set; }
        public Nullable<System.DateTime> ITEM_EXPIRY { get; set; }
    
        public virtual ITEMTYPE ITEMTYPE { get; set; }
    }
}
