//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPD_Section
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGS_PERSONS
    {
        public int LOG_ID { get; set; }
        public string OP_TYPE { get; set; }
        public int PERSON_ID { get; set; }
        public int HOUSE_ID { get; set; }
        public string NAME { get; set; }
        public int AGE { get; set; }
        public string GENDER { get; set; }
        public string PHONE_NO { get; set; }
    }
}
