//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPD_Section
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGS_INVENTORY
    {
        public int LOG_ID { get; set; }
        public string TABLE_TYPE { get; set; }
        public string OP_TYPE { get; set; }
        public int QUANTITY_CHANGE { get; set; }
        public int ITEM_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public int QUANTITY { get; set; }
    }
}
