//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPD_Section
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGS_HOUSES
    {
        public int LOG_ID { get; set; }
        public string OP_TYPE { get; set; }
        public int HOUSE_ID { get; set; }
        public int VILLAGE_ID { get; set; }
        public int NO_OF_PEOPLE { get; set; }
    }
}
