//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPD_Section
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISCELLANEOU
    {
        public int MISCELLANEOUS_ID { get; set; }
        public string MISCELLANEOUS_NAME { get; set; }
        public int QUANTITY { get; set; }
    }
}
