//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPD_Section
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sampledbEntities : DbContext
    {
        public sampledbEntities()
            : base("name=sampledbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<House> HOUSES { get; set; }
        public virtual DbSet<ITEM> ITEMS { get; set; }
        public virtual DbSet<ITEMTYPE> ITEMTYPES { get; set; }
        public virtual DbSet<MEDICINE> MEDICINES { get; set; }
        public virtual DbSet<PERSON> PERSONS { get; set; }
        public virtual DbSet<PRESCRIPTION> PRESCRIPTIONS { get; set; }
        public virtual DbSet<SYMPTOM> SYMPTOMS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<VILLAGE> VILLAGES { get; set; }
        public virtual DbSet<VISIT> VISITS { get; set; }
        public virtual DbSet<PRESCRIPTIONS_ARCHIVE> PRESCRIPTIONS_ARCHIVE { get; set; }
        public virtual DbSet<SYMPTOMS_ARCHIVE> SYMPTOMS_ARCHIVE { get; set; }
        public virtual DbSet<VISITS_ARCHIVE> VISITS_ARCHIVE { get; set; }
        public virtual DbSet<VIEW_PERSON_UID> VIEW_PERSON_UID { get; set; }
    }
}
