//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPD_Section
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESCRIPTION
    {
        public int PRESCRIPTION_ID { get; set; }
        public int VISIT_ID { get; set; }
        public int MEDICINE_ID { get; set; }
        public int QUANTITY { get; set; }
    
        public virtual MEDICINE MEDICINE { get; set; }
        public virtual VISIT VISIT { get; set; }
    }
}
