//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPD_Section
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYMPTOMS_ARCHIVE
    {
        public int SYMPTOM_ID { get; set; }
        public int VISIT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string SYMPTOM_NAME { get; set; }
    }
}
