//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPD_Section
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITS_ARCHIVE
    {
        public int VISIT_ID { get; set; }
        public int PERSON_ID { get; set; }
        public string PERSON_NAME { get; set; }
        public System.DateTime DATE { get; set; }
        public System.TimeSpan TIME { get; set; }
    }
}
